#!/bin/bash

build() {
    add_module "dm-crypt"
    add_module "dm-integrity"
    add_all_modules "/crypto/"

    add_binary "lsblk"
    add_binary "whiptail"
    add_binary "cryptsetup"
    add_binary "dmsetup"

    # cryptsetup calls pthread_create(), which dlopen()s libgcc_s.so.1
    add_binary "/usr/lib/libgcc_s.so.1"

    add_runscript
}

help() {
    cat <<HELPEOF
This hook finds an existing Linux root file system on any block device
HELPEOF
}
