#!/bin/bash

build() {
    add_file "/usr/bin/sysrescue-configuration.lua"
    add_binary "/usr/bin/lua"
    add_full_dir "/usr/lib/lua"
    add_full_dir "/usr/share/lua"

    # install our rules to handle the "nomdlvm" boot commandline option
    add_file /usr/lib/udev/rules.d/09-nomdlvm.rules
    add_file /usr/lib/udev/rules.d/61-nomdlvm.rules
}

help() {
    cat <<HELPEOF
This hook allows the configuration processing script to be installed with all its dependencies
HELPEOF
}
